# Generated by Django 2.1.5 on 2019-01-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raspberry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raspid', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SmileI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smileic', models.IntegerField()),
                ('pushed_dateI', models.DateTimeField(verbose_name='date published')),
                ('rasp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusa.raspberry')),
            ],
        ),
        migrations.CreateModel(
            name='SmileS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smilesc', models.IntegerField()),
                ('pushed_dateS', models.DateTimeField(verbose_name='date published')),
                ('rasp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusa.raspberry')),
            ],
        ),
    ]
